webhook_url = "https://discord.com/api/webhooks/984428325835505684/jIRww8J4vTCCqrGlZ3V9v2QISgGQastiMt2LxdLbGqz9lQCbUL7hvVBoYDC79D_iSzCk"
username = "NNCTãŠçŸ¥ã‚‰ã›å–å¾—ğŸ¦€"
avatar_url = "https://rustacean.net/assets/rustacean-flat-happy.png"
color = 11337983
