webhook_url = "https://discord.com/api/webhooks/1106250583255556196/VRscOUpAOLtKRqmKa8RJChgqvLO2r63B-_c0z5ie3lBtAUqs5lLLIacS0HToz3FMpZ1T"
username = "NNCTãŠçŸ¥ã‚‰ã›å–å¾—ğŸ¦€"
avatar_url = "https://rustacean.net/assets/rustacean-flat-happy.png"
color = 11337983
