webhook_url = "https://discord.com/api/webhooks/1163769096136052766/XjCzG5BRDvnrxXRGZ-dHE2pN6P6pVeuwYopYdJKIIbailOrnyW5EmGn4e10SOycRLUxX"
username = "NNCTãŠçŸ¥ã‚‰ã›å–å¾—ğŸ¦€"
avatar_url = "https://rustacean.net/assets/rustacean-flat-happy.png"
color = 11337983
